"""
topos_ai.formal_kan — Formal Left and Right Kan Extensions.

Constructs Lan_K X (left) and Ran_K X (right) Kan extensions for a
set-valued functor X: C → FinSet along a functor K: C → D over finite
categories, using the exact colimit / limit formulas.

Mathematical contracts
----------------------
**Left Kan extension** Lan_K X: D → FinSet

  (Lan_K X)(d)  =  colim_{(K ↓ d)}  X ∘ π_C

where (K ↓ d) is the comma category:
  • objects:   pairs (c, f) with f: K(c) → d  in D
  • morphisms: h: c → c'  in C  with  f' ∘ K(h) = f  in D

The colimit is represented as the quotient of  ∐_{(c,f)} X(c)  by the
equivalence relation generated by  x ∼ X(h)(x)  for every comma
morphism h: (c,f) → (c',f').

**Right Kan extension** Ran_K X: D → FinSet

  (Ran_K X)(d)  =  lim_{(d ↓ K)}  X ∘ π_C

where (d ↓ K) is the comma category:
  • objects:   pairs (c, g) with g: d → K(c)  in D
  • morphisms: h: c → c'  in C  with  K(h) ∘ g = g'  in D

The limit is the set of *matching families*: functions  s: (c,g) ↦ s_{c,g} ∈ X(c)
such that  X(h)(s_{c,g}) = s_{c',g'}  for every comma morphism h.

**Universal property** (checked by cardinality):

  |Nat(Lan_K X, Y)|  ==  |Nat(X, Y ∘ K)|   for every Y: D → FinSet
  |Nat(Y ∘ K, X)|   ==  |Nat(Y, Ran_K X)|  for every Y: D → FinSet

All data lives in plain Python dicts; no PyTorch dependency is required.
"""
from __future__ import annotations

from itertools import product
from typing import Any, Dict, FrozenSet, List, Optional, Tuple


# ---------------------------------------------------------------------------
# FiniteSetFunctor
# ---------------------------------------------------------------------------

class FiniteSetFunctor:
    """
    A functor F: C → FinSet over a FiniteCategory.

    Parameters
    ----------
    category : FiniteCategory
        The source category C.
    objects_map : dict[str, frozenset]
        Maps each object c ∈ C to the finite set F(c).
    morphism_map : dict[str, dict]
        Maps each morphism f ∈ C to the function  F(f): F(src) → F(tgt)
        represented as a dict ``{x: F(f)(x) for x in F(src)}``.
    validate : bool
        If True (default), run type-checking on construction.
    """

    def __init__(
        self,
        *,
        category,
        objects_map: Dict[str, FrozenSet],
        morphism_map: Dict[str, Dict],
        validate: bool = True,
    ):
        self.category = category
        self.objects_map: Dict[str, FrozenSet] = {
            k: frozenset(v) for k, v in objects_map.items()
        }
        self.morphism_map: Dict[str, Dict] = dict(morphism_map)
        if validate:
            self._validate()

    # ------------------------------------------------------------------
    def _validate(self):
        for obj in self.category.objects:
            if obj not in self.objects_map:
                raise ValueError(
                    f"FiniteSetFunctor: missing objects_map entry for {obj!r}"
                )
        for mor in self.category.morphisms:
            if mor not in self.morphism_map:
                raise ValueError(
                    f"FiniteSetFunctor: missing morphism_map entry for {mor!r}"
                )
            src = self.category.source(mor)
            tgt = self.category.target(mor)
            f_map = self.morphism_map[mor]
            for x in self.objects_map[src]:
                if x not in f_map:
                    raise ValueError(
                        f"FiniteSetFunctor: morphism_map[{mor!r}] missing element {x!r}"
                    )
                if f_map[x] not in self.objects_map[tgt]:
                    raise ValueError(
                        f"FiniteSetFunctor: morphism_map[{mor!r}]({x!r}) = "
                        f"{f_map[x]!r} ∉ {self.objects_map[tgt]}"
                    )

    # ------------------------------------------------------------------
    def apply_obj(self, obj: str) -> FrozenSet:
        """Return F(obj)."""
        return self.objects_map[obj]

    def apply_mor(self, mor: str) -> Dict:
        """Return the function dict for F(mor)."""
        return self.morphism_map[mor]

    def __repr__(self):
        return (
            f"FiniteSetFunctor("
            f"objects={list(self.objects_map)}, "
            f"sets={[len(s) for s in self.objects_map.values()]})"
        )


# ---------------------------------------------------------------------------
# Comma category helpers
# ---------------------------------------------------------------------------

def _comma_objects_K_down(K_obj: Dict, K_mor: Dict, C_cat, D_cat, d: str):
    """
    Objects of (K ↓ d): pairs (c, f) with f: K(c) → d in D.

    Returns list of (c, f_name) tuples.
    """
    result = []
    for c in C_cat.objects:
        kc = K_obj[c]
        for mor_name, (src, tgt) in D_cat.morphisms.items():
            if src == kc and tgt == d:
                result.append((c, mor_name))
    return result


def _comma_objects_d_down(K_obj: Dict, K_mor: Dict, C_cat, D_cat, d: str):
    """
    Objects of (d ↓ K): pairs (c, g) with g: d → K(c) in D.

    Returns list of (c, g_name) tuples.
    """
    result = []
    for c in C_cat.objects:
        kc = K_obj[c]
        for mor_name, (src, tgt) in D_cat.morphisms.items():
            if src == d and tgt == kc:
                result.append((c, mor_name))
    return result


# ---------------------------------------------------------------------------
# Left Kan Extension — colimit formula
# ---------------------------------------------------------------------------

def _build_left_kan_object(
    X: FiniteSetFunctor,
    K_obj: Dict,
    K_mor: Dict,
    D_cat,
    d: str,
):
    """
    Compute (Lan_K X)(d) as a frozenset of equivalence-class labels,
    plus the membership map  (c, f, x) → class_label.
    """
    C_cat = X.category
    comma_objs = _comma_objects_K_down(K_obj, K_mor, C_cat, D_cat, d)

    # Build coproduct elements
    elements = []
    for (c, f) in comma_objs:
        for x in sorted(X.apply_obj(c), key=str):
            elements.append((c, f, x))

    if not elements:
        return frozenset(), {}

    # Union-Find
    parent = {e: e for e in elements}

    def find(e):
        while parent[e] != e:
            parent[e] = parent[parent[e]]
            e = parent[e]
        return e

    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[ra] = rb

    # Generate equivalences from comma morphisms
    # Comma morphism: h: c → c' in C with compose(f', K(h)) = f in D
    for (c, f_mor) in comma_objs:
        for (c2, f2_mor) in comma_objs:
            for h, (hsrc, htgt) in C_cat.morphisms.items():
                if hsrc != c or htgt != c2:
                    continue
                kh = K_mor[h]
                # Check compose(f2, kh) = f  (f2 after kh)
                if D_cat.target(kh) != D_cat.source(f2_mor):
                    continue
                try:
                    composed = D_cat.compose(f2_mor, kh)
                except ValueError:
                    continue
                if composed != f_mor:
                    continue
                # h is a valid comma morphism (c,f) → (c',f')
                h_map = X.apply_mor(h)
                for x in X.apply_obj(c):
                    y = h_map[x]
                    a_el = (c, f_mor, x)
                    b_el = (c2, f2_mor, y)
                    if a_el in parent and b_el in parent:
                        union(a_el, b_el)

    # Collect roots as class labels
    membership: Dict[Tuple, Any] = {}
    for e in elements:
        membership[e] = find(e)

    class_labels = frozenset(set(membership.values()))
    return class_labels, membership


def left_kan_extension(
    X: FiniteSetFunctor,
    K_obj: Dict[str, str],
    K_mor: Dict[str, str],
    D_cat,
) -> FiniteSetFunctor:
    """
    Compute the left Kan extension  Lan_K X: D → FinSet.

    Parameters
    ----------
    X : FiniteSetFunctor  on C
    K_obj : dict[C_obj → D_obj]  — object map of K: C → D
    K_mor : dict[C_mor → D_mor]  — morphism map of K: C → D
    D_cat : FiniteCategory — the target category D

    Returns
    -------
    FiniteSetFunctor on D_cat representing Lan_K X.
    """
    # Step 1: compute each (Lan_K X)(d)
    lan_obj_sets: Dict[str, FrozenSet] = {}
    lan_membership: Dict[str, Dict] = {}

    for d in D_cat.objects:
        cls_labels, membership = _build_left_kan_object(X, K_obj, K_mor, D_cat, d)
        lan_obj_sets[d] = cls_labels
        lan_membership[d] = membership  # (c, f, x) → class label

    # Step 2: compute morphism actions (Lan_K X)(g: d → d')
    # Given a class label in (Lan_K X)(d), its representative (c, f, x)
    # maps to (c, compose(g, f), x) in (Lan_K X)(d').
    lan_mor_maps: Dict[str, Dict] = {}

    for g_name, (d_src, d_tgt) in D_cat.morphisms.items():
        src_membership = lan_membership[d_src]
        tgt_membership = lan_membership[d_tgt]
        g_map: Dict[Any, Any] = {}

        # For each class label in the source, find its image in target
        seen_classes: Dict[Any, Any] = {}
        for (c, f_mor, x), cls_label in src_membership.items():
            if cls_label in seen_classes:
                continue
            # Map (c, f: K(c)→d_src, x)  to  (c, g∘f: K(c)→d_tgt, x)
            # Need g∘f in D: compose(g_name, f_mor) — g after f
            if D_cat.target(f_mor) != D_cat.source(g_name):
                continue
            try:
                gf = D_cat.compose(g_name, f_mor)
            except ValueError:
                continue
            tgt_el = (c, gf, x)
            if tgt_el in tgt_membership:
                seen_classes[cls_label] = tgt_membership[tgt_el]
        g_map = dict(seen_classes)
        lan_mor_maps[g_name] = g_map

    return FiniteSetFunctor(
        category=D_cat,
        objects_map=lan_obj_sets,
        morphism_map=lan_mor_maps,
        validate=False,
    )


# ---------------------------------------------------------------------------
# Right Kan Extension — limit formula
# ---------------------------------------------------------------------------

def right_kan_extension(
    X: FiniteSetFunctor,
    K_obj: Dict[str, str],
    K_mor: Dict[str, str],
    D_cat,
) -> FiniteSetFunctor:
    """
    Compute the right Kan extension  Ran_K X: D → FinSet.

    (Ran_K X)(d) is the set of all *matching families*: dicts
    { (c, g): x }  for each comma object (c, g: d → K(c)),
    satisfying  X(h)( s_{c,g} ) = s_{c', K(h)∘g }  for every
    comma morphism h: c → c'  with  K(h)∘g = g'  in D.

    Represented as frozensets of  ((c, g), x)  pairs for hashability.
    """
    C_cat = X.category

    ran_obj_sets: Dict[str, FrozenSet] = {}
    ran_families: Dict[str, List[Dict]] = {}  # d → list of raw dict families

    for d in D_cat.objects:
        comma_objs = _comma_objects_d_down(K_obj, K_mor, C_cat, D_cat, d)

        # Enumerate all assignments  (c, g) ↦ x ∈ X(c)
        if not comma_objs:
            # Empty comma category: unique empty family
            ran_obj_sets[d] = frozenset({frozenset()})
            ran_families[d] = [{}]
            continue

        domains = [sorted(X.apply_obj(c), key=str) for (c, _) in comma_objs]
        families = []
        for assignment in product(*domains):
            s = {cg: v for cg, v in zip(comma_objs, assignment)}
            # Check matching condition
            valid = True
            for (c, g_mor) in comma_objs:
                for (c2, g2_mor) in comma_objs:
                    for h, (hsrc, htgt) in C_cat.morphisms.items():
                        if hsrc != c or htgt != c2:
                            continue
                        kh = K_mor[h]
                        # Check K(h)∘g = g' in D: compose(kh, g_mor) = g2_mor
                        if D_cat.source(kh) != D_cat.target(g_mor):
                            continue
                        try:
                            composed = D_cat.compose(kh, g_mor)
                        except ValueError:
                            continue
                        if composed != g2_mor:
                            continue
                        # h is a valid comma morphism: (c, g) → (c', g')
                        h_map = X.apply_mor(h)
                        if h_map.get(s[(c, g_mor)]) != s[(c2, g2_mor)]:
                            valid = False
                            break
                    if not valid:
                        break
                if not valid:
                    break
            if valid:
                families.append(s)

        # Convert each family to a frozenset for hashability
        frozen_families = frozenset(
            frozenset(((c, g), v) for (c, g), v in fam.items())
            for fam in families
        )
        ran_obj_sets[d] = frozen_families
        ran_families[d] = families

    # Morphism action (Ran_K X)(f: d → d')
    # Given a matching family s ∈ (Ran_K X)(d), produce s' ∈ (Ran_K X)(d') by
    # s'_{c, g: d'→K(c)} = s_{c, compose(g, f): d→K(c)}
    ran_mor_maps: Dict[str, Dict] = {}

    for f_name, (d_src, d_tgt) in D_cat.morphisms.items():
        src_families = ran_families[d_src]
        tgt_comma = _comma_objects_d_down(K_obj, K_mor, C_cat, D_cat, d_tgt)

        # Index source families by frozenset form
        def _freeze(fam: Dict) -> FrozenSet:
            return frozenset(((c, g), v) for (c, g), v in fam.items())

        # Build source index  frozenset → raw dict
        src_index = {_freeze(s): s for s in src_families}

        f_map: Dict[FrozenSet, FrozenSet] = {}
        tgt_families = ran_families[d_tgt]
        tgt_index = {_freeze(s): s for s in tgt_families}

        for src_fs, src_dict in src_index.items():
            # Build the pushed-forward family on (d_tgt ↓ K)
            pushed: Dict = {}
            ok = True
            for (c, g_mor) in tgt_comma:
                # compose(g_mor, f_name): d_src → K(c)
                if D_cat.source(f_name) != D_cat.source(g_mor):
                    pass  # f: d_src→d_tgt, g: d_tgt→K(c), compose(g, f): d_src→K(c)
                if D_cat.target(f_name) != D_cat.source(g_mor):
                    ok = False
                    break
                try:
                    gf = D_cat.compose(g_mor, f_name)
                except ValueError:
                    ok = False
                    break
                if (c, gf) not in src_dict:
                    ok = False
                    break
                pushed[(c, g_mor)] = src_dict[(c, gf)]
            if not ok:
                continue
            pushed_fs = frozenset(((c, g), v) for (c, g), v in pushed.items())
            if pushed_fs in tgt_index:
                f_map[src_fs] = pushed_fs
        ran_mor_maps[f_name] = f_map

    return FiniteSetFunctor(
        category=D_cat,
        objects_map=ran_obj_sets,
        morphism_map=ran_mor_maps,
        validate=False,
    )


# ---------------------------------------------------------------------------
# Natural transformations between FiniteSetFunctors
# ---------------------------------------------------------------------------

def all_natural_transformations(
    F: FiniteSetFunctor,
    G: FiniteSetFunctor,
) -> List[Dict[str, Dict]]:
    """
    Enumerate all natural transformations  α: F → G.

    Both F and G must be FiniteSetFunctors on the same category.
    A natural transformation is a family  {α_d: F(d) → G(d)}  satisfying
    the naturality square for every morphism.

    Returns a list of dicts  {obj_name: {x: α_d(x)}}  — one per nat. trans.
    """
    assert F.category is G.category or (
        F.category.objects == G.category.objects
        and F.category.morphisms == G.category.morphisms
    ), "F and G must share the same category"
    cat = F.category

    objects = cat.objects
    # Enumerate all families of component functions
    # For each object d, enumerate all functions F(d) → G(d)
    obj_domains = {}
    obj_component_choices = {}
    for d in objects:
        fd = sorted(F.apply_obj(d), key=str)
        gd = sorted(G.apply_obj(d), key=str)
        if not fd:
            obj_component_choices[d] = [{}]
        elif not gd:
            obj_component_choices[d] = []  # no functions possible unless fd is empty
        else:
            choices = []
            for outputs in product(gd, repeat=len(fd)):
                choices.append(dict(zip(fd, outputs)))
            obj_component_choices[d] = choices

    # Cartesian product over all objects
    all_components = list(product(*[obj_component_choices[d] for d in objects]))

    result = []
    for combo in all_components:
        alpha = dict(zip(objects, combo))
        # Check naturality: for every morphism f: src → tgt,
        # G(f) ∘ α_src = α_tgt ∘ F(f)
        natural = True
        for mor in cat.morphisms:
            src = cat.source(mor)
            tgt = cat.target(mor)
            Ff = F.apply_mor(mor)
            Gf = G.apply_mor(mor)
            alpha_src = alpha[src]
            alpha_tgt = alpha[tgt]
            for x in F.apply_obj(src):
                # LHS: G(f)(α_src(x))
                lhs = Gf.get(alpha_src.get(x))
                # RHS: α_tgt(F(f)(x))
                rhs = alpha_tgt.get(Ff.get(x))
                if lhs != rhs:
                    natural = False
                    break
            if not natural:
                break
        if natural:
            result.append(alpha)
    return result


# ---------------------------------------------------------------------------
# Universal property verification
# ---------------------------------------------------------------------------

def verify_left_kan_universal_property(
    X: FiniteSetFunctor,
    K_obj: Dict[str, str],
    K_mor: Dict[str, str],
    D_cat,
    Y: FiniteSetFunctor,
) -> bool:
    """
    Check  |Nat(Lan_K X, Y)|  ==  |Nat(X, Y ∘ K)|.

    Constructs both sets of natural transformations explicitly and compares
    their cardinalities.  Returns True iff they match.

    Parameters
    ----------
    X   : FiniteSetFunctor on C
    K_obj / K_mor : functor K: C → D
    D_cat : target category D
    Y   : FiniteSetFunctor on D
    """
    lan = left_kan_extension(X, K_obj, K_mor, D_cat)
    nats_lhs = all_natural_transformations(lan, Y)

    # Build Y ∘ K as a FiniteSetFunctor on C
    C_cat = X.category
    yok_obj_map = {c: Y.apply_obj(K_obj[c]) for c in C_cat.objects}
    yok_mor_map = {h: Y.apply_mor(K_mor[h]) for h in C_cat.morphisms}
    YoK = FiniteSetFunctor(
        category=C_cat,
        objects_map=yok_obj_map,
        morphism_map=yok_mor_map,
        validate=False,
    )
    nats_rhs = all_natural_transformations(X, YoK)

    return len(nats_lhs) == len(nats_rhs)


def verify_right_kan_universal_property(
    X: FiniteSetFunctor,
    K_obj: Dict[str, str],
    K_mor: Dict[str, str],
    D_cat,
    Y: FiniteSetFunctor,
) -> bool:
    """
    Check  |Nat(Y ∘ K, X)|  ==  |Nat(Y, Ran_K X)|.

    Returns True iff the cardinalities match.
    """
    ran = right_kan_extension(X, K_obj, K_mor, D_cat)
    nats_lhs = all_natural_transformations(Y, ran)

    # Build Y ∘ K
    C_cat = X.category
    yok_obj_map = {c: Y.apply_obj(K_obj[c]) for c in C_cat.objects}
    yok_mor_map = {h: Y.apply_mor(K_mor[h]) for h in C_cat.morphisms}
    YoK = FiniteSetFunctor(
        category=C_cat,
        objects_map=yok_obj_map,
        morphism_map=yok_mor_map,
        validate=False,
    )
    nats_rhs = all_natural_transformations(YoK, X)

    return len(nats_lhs) == len(nats_rhs)


# ---------------------------------------------------------------------------
# Unit of the left Kan extension
# ---------------------------------------------------------------------------

def left_kan_unit(
    X: FiniteSetFunctor,
    K_obj: Dict[str, str],
    K_mor: Dict[str, str],
    D_cat,
) -> Dict[str, Dict]:
    """
    Compute the unit  η: X → (Lan_K X) ∘ K.

    For each c ∈ C, η_c: X(c) → (Lan_K X)(K(c)) maps x to the equivalence
    class of (c, id_{K(c)}, x).

    Returns a dict  {c_name: {x: class_label}}.
    """
    C_cat = X.category
    lan = left_kan_extension(X, K_obj, K_mor, D_cat)
    unit: Dict[str, Dict] = {}

    for c in C_cat.objects:
        kc = K_obj[c]
        id_kc = D_cat.identities[kc]
        membership = {}
        for d in D_cat.objects:
            if d != kc:
                continue
            _, mem = _build_left_kan_object(X, K_obj, K_mor, D_cat, d)
            for x in X.apply_obj(c):
                key = (c, id_kc, x)
                if key in mem:
                    membership[x] = mem[key]
        unit[c] = membership

    return unit
