import re
import subprocess


class Lean4VerificationBridge:
    """
    Convert a simple implication chain into Lean 4 syntax and optionally run
    the local Lean compiler.

    This bridge verifies the generated symbolic proposition when Lean is
    installed. It does not prove that an upstream neural confidence score is
    correct; the confidence is emitted only as metadata.
    """

    def __init__(self, entities):
        self.entities = [self._clean_identifier(entity) for entity in entities]

    @staticmethod
    def _clean_identifier(entity):
        cleaned = re.sub(r"[^a-zA-Z0-9_]", "_", str(entity).lower()).strip("_")
        if not cleaned:
            cleaned = "entity"
        if cleaned[0].isdigit():
            cleaned = "v_" + cleaned
        return cleaned

    def _generate_lean_code(self, chain, confidence, has_defeater=False):
        """Generate Lean 4 code for a chain A -> B -> ... -> Z.
           If has_defeater is True, the last implication becomes a contradiction (Not).
        """
        if not chain or len(chain) < 2:
            return "Error: expected a chain with at least two nodes."

        lean_code = [
            "-- ==========================================",
            "-- AUTO-GENERATED BY TOPOS-AI TRANSPILER",
            f"-- Confidence Score: {confidence:.4f}",
            "-- Note: confidence is metadata, not a Lean theorem.",
            "-- ==========================================",
            "",
        ]

        vars_str = " ".join(self.entities[i] for i in chain)

        hypotheses = []
        for idx in range(len(chain) - 1):
            h_name = f"h{idx + 1}"
            u = self.entities[chain[idx]]
            v = self.entities[chain[idx + 1]]
            if idx == len(chain) - 2 and has_defeater:
                hypotheses.append(f"({h_name} : {u} -> Not {v})")
            else:
                hypotheses.append(f"({h_name} : {u} -> {v})")

        start_node = self.entities[chain[0]]
        end_node = self.entities[chain[-1]]

        if has_defeater:
            theorem_name = f"topos_proof_{start_node}_to_Not_{end_node}"
            lean_code.append(
                f"theorem {theorem_name} ({vars_str} : Prop) "
                f"{' '.join(hypotheses)} : {start_node} -> Not {end_node} := by"
            )
        else:
            theorem_name = f"topos_proof_{start_node}_to_{end_node}"
            lean_code.append(
                f"theorem {theorem_name} ({vars_str} : Prop) "
                f"{' '.join(hypotheses)} : {start_node} -> {end_node} := by"
            )

        lean_code.append("  intro x")

        for h_name in reversed([f"h{idx + 1}" for idx in range(len(chain) - 1)]):
            lean_code.append(f"  apply {h_name}")
        lean_code.append("  exact x")

        return "\n".join(lean_code)

    def prove_theorem(self, chain, confidence, has_defeater=False, filename=None):
        """
        Write generated Lean code and run `lean` if it is available.

        Returns:
            (True, script, output) when Lean accepts the generated proposition.
            (False, script, output) when Lean rejects it.
            (None, script, reason) when Lean cannot be run locally.
        """
        import time
        if filename is None:
            filename = f"topos_proof_{int(time.time())}.lean"

        lean_script = self._generate_lean_code(chain, confidence, has_defeater)

        print(f"\n[LEAN KERNEL] Writing '{filename}'...")
        with open(filename, "w", encoding="utf-8") as f:
            f.write(lean_script)

        print("[LEAN KERNEL] Looking for local Lean 4 compiler...")
        try:
            result = subprocess.run(["lean", filename], capture_output=True, text=True, timeout=10)
            lean_output = (result.stdout + "\n" + result.stderr).strip()

            if result.returncode == 0:
                print("[FORMAL CHECK PASSED] Lean accepted the generated proposition.")
                print("   This checks the symbolic chain, not the neural confidence score.")
                return True, lean_script, lean_output

            print("[FORMAL CHECK FAILED] Lean rejected the generated proposition.")
            print(f"   Details:\n{lean_output}")
            return False, lean_script, lean_output

        except FileNotFoundError:
            print("[SYSTEM WARNING] 'lean' command was not found in PATH.")
            print(f"   Generated proof file is available at '{filename}'.")
            return None, lean_script, "Compiler Not Found"
        except subprocess.TimeoutExpired:
            print("[SYSTEM WARNING] Lean compiler timed out.")
            return None, lean_script, "Timeout"
