import subprocess
import tempfile

class Lean4VerificationBridge:
    """
    [NÖRO-SEMBOLİK İSPAT KÖPRÜSÜ]
    ToposAI'nin nöral (sayısal) matris çarpımlarıyla bulduğu çıkarımları, 
    saf matematiksel (sembolik) teorem ispatlama dili olan 'Lean 4' sentaksına 
    çevirir (Transpile) ve arka planda işletim sisteminin (OS) Lean 4 derleyicisini
    (Compiler) çalıştırarak sonucun kanun hükmünde (Axiomatic) doğrulanmasını sağlar.
    """
    def __init__(self, entities):
        # Lean değişken isimleri küçük harf ve boşluksuz (Underscore) olmalıdır.
        self.entities = [e.replace(" ", "_").lower() for e in entities]

    def _generate_lean_code(self, chain, confidence):
        """Bulunan mantık zincirini Lean 4 'Theorem' metnine dönüştürür."""
        if not chain or len(chain) < 2:
            return "Hata: Geçerli bir zincir yok."
            
        lean_code = []
        lean_code.append("-- ==========================================")
        lean_code.append("-- AUTO-GENERATED BY TOPOS-AI TRANSPILER")
        lean_code.append(f"-- Confidence Score: {confidence:.4f}")
        lean_code.append("-- Target Theorem: Formal Proof of Topos Reasoning")
        lean_code.append("-- ==========================================\n")
        
        # 1. Değişken Tanımları (Varlıklar)
        vars_str = " ".join([self.entities[i] for i in chain])
        lean_code.append(f"variable ({vars_str} : Prop)")
        
        # 2. Hipotezler (Zincirin Halka Bağlantıları)
        hypotheses = []
        for idx in range(len(chain) - 1):
            h_name = f"h{idx+1}"
            u = self.entities[chain[idx]]
            v = self.entities[chain[idx+1]]
            lean_code.append(f"variable ({h_name} : {u} → {v})")
            hypotheses.append(h_name)
            
        # 3. Teoremin Kendisi (A -> Sonuç)
        start_node = self.entities[chain[0]]
        end_node = self.entities[chain[-1]]
        theorem_name = f"topos_proof_{start_node}_to_{end_node}"
        
        lean_code.append(f"\n-- ToposAI'nin iddia ettiği nihai sonuç:")
        lean_code.append(f"theorem {theorem_name} : {start_node} → {end_node} := by")
        
        # 4. İspatın (Proof) İnşası (Curry-Howard-Lambek Yazılımı)
        lean_code.append("  -- Curry-Howard correspondence via functional composition")
        lean_code.append(f"  intro x")
        
        proof_call = "x"
        for h in hypotheses:
            proof_call = f"({h} {proof_call})"
            
        lean_code.append(f"  exact {proof_call}")

        return "\n".join(lean_code)

    def prove_theorem(self, chain, confidence, filename="topos_proof.lean"):
        """
        Zinciri Lean 4 koduna çevirir, diske yazar ve derleyiciyi (CLI)
        kullanarak matematiksel olarak doğrulamaya çalışır.
        """
        lean_script = self._generate_lean_code(chain, confidence)
        
        print(f"\n[LEAN KERNEL] '{filename}' dosyası oluşturuluyor...")
        with open(filename, "w", encoding="utf-8") as f:
            f.write(lean_script)
            
        print("[LEAN KERNEL] Sistemde Lean 4 derleyicisi (Compiler) aranıyor...")
        try:
            # Lean derleyicisini çalıştır
            result = subprocess.run(['lean', filename], capture_output=True, text=True, timeout=10)
            
            # stdout ve stderr'i birleştir ki Lean'in hata/başarı mesajını tam görelim
            lean_output = (result.stdout + "\n" + result.stderr).strip()
            
            if result.returncode == 0:
                print("✅ [FORMAL KANIT BAŞARILI]: Lean 4 derleyicisi hiçbir hata bulmadı.")
                print("   AI'ın bulduğu Teorem matematiksel olarak KUSURSUZDUR!")
                return True, lean_script, lean_output
            else:
                print("❌ [FORMAL KANIT BAŞARISIZ]: Lean 4 derleyicisi hata fırlattı.")
                print(f"   Detay:\n{lean_output}")
                return False, lean_script, lean_output
                
        except FileNotFoundError:
            print("⚠️ [SİSTEM UYARISI]: 'lean' komutu bulunamadı. (Lean 4 yüklü değil veya PATH'te yok).")
            print(f"   Ancak ToposAI, kanıt dosyasını ('{filename}') başarıyla üretti.")
            print("   Bu dosyayı Lean yüklü bir sistemde 'lean topos_proof.lean' ile manuel doğrulayabilirsiniz.")
            return None, lean_script, "Compiler Not Found"
        except subprocess.TimeoutExpired:
            print("⚠️ [SİSTEM UYARISI]: Lean derleyicisi zaman aşımına uğradı (Timeout).")
            return None, lean_script, "Timeout"
